{{- $ns := .Values.namespace.name | default (printf "tenant-%s" .Values.orgId) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scan-sa
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/part-of: flowsyc
    flowsyc.io/org-id: {{ .Values.orgId }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId }}
  {{- end }}
